export const SHOW_WORLD = 'SHOW_WORLD';

{/*
  Add and export SHOW_DIRECTOR and SHOW_MODEL action types
  */}

  {/* ONCE YOU HAVE REFACTORED THE FILMS AND STARSHIPS COMPONENTS,
    AND ADDED THEIR APPROPIATE ACTIONS, ACTION TYPES, AND REDUCERS, UNCOMMENT THIS
    CODE BLOCK AND DELETE THIS COMMENT.

  export const DETAILS = 'DETAILS';

  */}
